---
# Imutabilidade e idempotência: ao invés de baixar de https://get.k3s.io, usa cópia local congelada no tempo
- name: Distribute K3s install script
  ansible.builtin.copy:
    src: "./assets/k3s-install.sh"
    dest: /usr/local/bin/k3s-install.sh
    owner: root
    group: root
    mode: 0755

- name: Download K3s binary
  when: airgap_dir is undefined
  ansible.builtin.command:
    cmd: /usr/local/bin/k3s-install.sh
  environment:
    INSTALL_K3S_SKIP_START: "true"
    INSTALL_K3S_VERSION: "{{ k3s_version }}"
    INSTALL_K3S_EXEC: "agent"
  changed_when: true

- name: Copy K3s service file
  ansible.builtin.template:
    src: "k3s-agent.service.j2"
    dest: "{{ systemd_dir }}/k3s-agent.service"
    owner: root
    group: root
    mode: 0755

- name: Enable and check K3s service
  ansible.builtin.systemd:
    name: k3s-agent
    daemon_reload: true
    state: restarted
    enabled: true
